-- MySQL Script generated by MySQL Workbench
-- Sat Dec 16 11:46:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scheduler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scheduler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scheduler` DEFAULT CHARACTER SET utf8 ;
USE `scheduler` ;

-- -----------------------------------------------------
-- Table `scheduler`.`vecaki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`vecaki` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(255) NULL,
  `parent_name` VARCHAR(255) NULL,
  `contact_phone` VARCHAR(255) NULL,
  `nick_name` VARCHAR(45) NULL,
  `password` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduler`.`timeslot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`timeslot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` TIME NULL,
  `is_available` TINYINT(1) NULL,
  `vecaki_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timeslot_vecaki_idx` (`vecaki_id` ASC),
  CONSTRAINT `fk_timeslot_vecaki`
    FOREIGN KEY (`vecaki_id`)
    REFERENCES `scheduler`.`vecaki` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scheduler`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`subject` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scheduler`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`teacher` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `contact_phone` VARCHAR(50) NULL DEFAULT NULL,
  `nick_name` VARCHAR(45) NULL,
  `password` VARCHAR(50) NULL,
  `subject_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teacher_subject1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_teacher_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `scheduler`.`subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scheduler`.`inter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`inter` (
  `timeslot_id` INT NOT NULL,
  `teacher_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`timeslot_id`, `teacher_id`),
  INDEX `fk_inter_teacher1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_inter_timeslot1`
    FOREIGN KEY (`timeslot_id`)
    REFERENCES `scheduler`.`timeslot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inter_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `scheduler`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
