-- MySQL Script generated by MySQL Workbench
-- Thu Dec 28 13:44:05 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scheduler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scheduler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scheduler` DEFAULT CHARACTER SET utf8 ;
USE `scheduler` ;

-- -----------------------------------------------------
-- Table `scheduler`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`subject` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scheduler`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`teacher` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `contact_phone` VARCHAR(50) NULL DEFAULT NULL,
  `subject_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teacher_subject1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_teacher_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `scheduler`.`subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `scheduler`.`vecaki`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scheduler`.`vecaki` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(255) NULL,
  `parent_name` VARCHAR(255) NULL,
  `contact_phone` VARCHAR(255) NULL,
  `time` VARCHAR(20) NULL,
  `is_avaliable` TINYINT(1) NULL,
  `teacher_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vecaki_teacher1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_vecaki_teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `scheduler`.`teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
